### PR TITLE
Adds the --remove-files flag to the tar commands

### LINKED ISSUE #50: tar: director-backup.tar: Cannot write: No space left on device
Hi,
I am getting the error "tar: director-backup.tar: Cannot write: No space left on device, tar: Error is not recoverable: exiting now", when running the pipeline.
I have increased the space for Bosh Director in PAS tile, But still getting the same error.
Could any one help me in understanding where exactly, it was loading the temporary ".tar" files, before moving them to Storage Account.

Thanks in advance.

### PR DESCRIPTION
**Pull request by mike-carey**
Though this does not completely fix #50, it will at least cleanup as it is archiving.

### CODE REVIEW

**Comment by gmrodgers** [comment]
Hey @mike-carey, thanks for the PR.  We have scheduled the above story to look into your PR!

**Comment by alamages** [comment]
Hello @mike-carey , for not picking this one up sooner! We will merge it. But as you can see there is a pending build in the pipeline. This can be resolved if you rebase your branch with the latest master to pick up some changes that happen in the repo since you open the PR. 

Would you like to rebase it and re-push? Or if you give us the access we can do it and then merge it. Up to you, let us know and thanks again for the contribution!

**Comment by mike-carey** [comment]
Hey @alamages, thanks for your patience!  This update got buried in my email and I finally stumbled upon it.  😆

**Comment by gmrodgers** [comment]
Hey thanks for the update! Looks good to merge.

**Pull request merged**
