### PR TITLE
add azure example that doesn't store multiple copies of the backup

### PR DESCRIPTION
**Pull request by patrick-huber-pivotal**
I know this breaks from the convention of the other examples, but due to the way concourse handles resources, inputs and outputs, the backups were getting copied multiple times between tasks. In the event that a backup would fail, the copies would be stored for a very long time. I tried to use `on_failure`, `on_success` and `ensure` all of which copy the backup. Using caches also didn't help as the cache is only shared within the same pipeline+job+task+step combination.

In this example, each backup runs in a single task. Rollback is handled within bash and the `az` cli drives the upload to azure blobs. It does have to wrap the output of the ert backup in a tgz file, which takes up a little more space on disk but it was better than using a tar file and waiting for it to upload over the network (network is slower than disk in most cases https://serverfault.com/a/238534).  

I changed the base image to the azure cli base image as it was much easier to copy in `om` than install the azure cli. Further improvement could be to package this into a single base image but that would take extra work to maintain. 

Also handling the bosh director in no_proxy as not all customers think to put the IP address of the director in the no_proxy. 

When each script exits, it will always cleanup after its self. It only runs the bbr cleanup task if the bbr backup fails.

### CODE REVIEW

**Comment by gmrodgers** [comment]
Hey @patrick-huber-pivotal 

Thanks for the PR.  Just a few questions!
* What is the issue that this PR is solving?
* Is there an issue with our original tasks when using a concourse deployed on azure or is it an issue with using this task with a PCF environment deployed on Azure?  We currently do not test this tasks with either of these use cases.
* Are you experiencing issues with our tasks that are blocking you?  
* Is there a customer blocked on this?

Thanks!

PS sorry for the slow reply!

**Comment by patrick-huber-pivotal** [comment]
Hi @gmrodgers

Q: What is the issue that this PR is solving?
A: there are a few things this PR covers.
* The first is azure as an example. I originally had patched out the S3 resources with the azure storage resource and that worked until I ran out of disk on the workers
* Running out of disk on the workers. The usage of the tasks in a pipeline works by making copies of the backups for each task and resource that touches the input/output (this is a concourse limitation). With a 75GB backup, copied 3 times across 5 foundations, space quickly is eaten up.
* When a build fails, storage is retained until the build is later garbage collected. This means that multiple copies from multiple foundations can sit on disk for an unknown duration.
 
Q: Is there an issue with our original tasks when using a concourse deployed on azure or is it an issue with using this task with a PCF environment deployed on Azure? We currently do not test this tasks with either of these use cases.
A: no, it works fine if you yaml patch the S3 resources with the azure storage resource https://github.com/pivotal-cf/azure-blobstore-resource . Like I mentioned, this was my first attempt. I switched to a self contained task when I ran into scaling issues. Each of our workers had 800GB of disk so scaling up was only getting us so far.

Q: Are you experiencing issues with our tasks that are blocking you?
Is there a customer blocked on this?
A: yes, I was unable to use the existing tasks at the customer because when combined in a pipeline the inputs and outputs store multiple copies of the backups. I created this implementation to unblock the customer.

**Comment by gmrodgers** [comment]
Hey again Patrick,

One more question; is this a `bbr director backup` or a `bbr deployment backup` that is causing the issue?

We are hesitant to merge in the PR for two reasons, namely:

+ We feel that using multiple tasks in Concourse is idiomatically correct.  I.e. Not having a task that would perform, cleanup, and upload the backup, but instead the current implementation where we have a task for each
+ The PR would mean that the tasks we are maintaining would be tied to a specific storage service (i.e. Azure) and would not give customers the granularity to plug-and-play with three separate tasks.  Whilst the example pipelines do specify S3 as their storage, we do not promote these to be used and should only be seen for guidance.  Having storage-specific implementation detail in a task, like in the PR, would have narrow the scope of the task's applicability.

We have created [an issue with Concourse](https://github.com/concourse/concourse/issues/3543) to see if they have ideas for solutions/mitigations for the large file transfers between disk causing workers to run out of disk space.

Best,
Glen

**Comment by patrick-huber-pivotal** [comment]
That makes sense, it is really a work around of limitations with concourse.

**Comment by gmrodgers** [comment]
We have created a topic here https://discuss.concourse-ci.org/t/concourse-workers-running-out-of-disk-space/1235 to explore the issue further.  Feel free to follow up if there is a solution that we could work with!

Closing this PR for now and will revisit if there's a further update

**Pull request closed without merging**
