### PR TITLE
Adding cleanup task as recommended by the PCF docs.

### PR DESCRIPTION
**Pull request by shinji62**
As state in the docs https://docs.pivotal.io/pivotalcf/2-0/customizing/backup-restore/backup-pcf-bbr.html#bbr-backup . it's recommanded if the backup fail to run the `cleanup` task.

I just added suppot for ERT and DIRECTOR

### CODE REVIEW

**Comment by shinji62** [comment]
@MirahImage Any chnace to get this merge ?

**Comment by MirahImage** [comment]
@shinji62 there is a story in our backlog and it's coming up soon

**Comment by MirahImage** [comment]
Hi, 

If you can change the permissions on `tasks/bbr-cleanup-director/task.sh` to be executable, we can merge the pull request.

Best,
Mirah, @alamages, and @jamesjoshuahill

**Comment by shinji62** [comment]
Ok will do. Sorry for the miss

**Comment by shinji62** [comment]
@MirahImage done.

**Pull request merged**
